version: 2.1

executors:
  dotnet-env:
    docker:
      - image: microsoft/dotnet:2.1-sdk

jobs:
  quick-build:
    executor: dotnet-env
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test --no-build Netpips.Tests --filter "TestCategory!=Filebot&TestCategory!=ThirdParty"

  complete-build:
    executor: dotnet-env
    steps:
      - checkout
      - run:
          name: filebot
          command: |
            apt-get update -y
            apt-get install -y openjdk-8-jre 
            wget -O filebot.deb 'https://app.filebot.net/download.php?type=deb&arch=amd64'
            dpkg -i filebot.deb
            filebot -version
            echo -e "$FILEBOT_LOGIN\n$FILEBOT_PASSWORD" | filebot -script fn:configure
      - run: apt-get install -y transmission-cli transmission-common transmission-daemon
      - run: apt-get install -y mediainfo
      - run: apt-get install -y aria2
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test --no-build Netpips.Tests

  deploy-staging:
    executor: dotnet-env
    steps:
      - add_ssh_keys:
          fingerprints:
            - "89:20:1d:8d:12:f1:8b:a3:4b:5f:21:6d:99:84:7a:8a"
      - run:
          name: Say Hello
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_STAGING_USER@$SSH_STAGING_HOST "./deploy.sh $CIRCLE_BRANCH $CIRCLE_SHA1"

workflows:
  version: 2
  default-workflow:
    jobs:
      - quick-build:
          filters:
            branches:
              ignore:
                - staging
                - production

  staging-workflow:
    jobs:
      - quick-build:
          filters:
            branches:
              only: staging