version: 2.1

executors:
  dotnet-env:
    docker:
      - image: microsoft/dotnet:2.1-sdk

jobs:

  wait:
    machine: true
    steps:
      - run: sleep 10

  display:
    machine: true
    steps:
      - run: ls -la

  build-simple:
    executor: dotnet-env
    steps:
      - checkout
      - run: dotnet test Netpips.Tests --filter "TestCategory!=Filebot&TestCategory!=ThirdParty"

  build-complete:
    executor: dotnet-env
    steps:
      - checkout
      - run:
          name: filebot install
          command: |
            apt-get update -y
            apt-get install -y openjdk-8-jre 
            wget -O filebot.deb 'https://app.filebot.net/download.php?type=deb&arch=amd64'
            dpkg -i filebot.deb
            filebot -version
            echo -e "$FILEBOT_LOGIN\n$FILEBOT_PASSWORD" | filebot -script fn:configure
      - run: apt-get install -y transmission-cli transmission-common transmission-daemon
      - run: apt-get install -y mediainfo
      - run: apt-get install -y aria2
      - run: dotnet test Netpips.Tests

  deploy-ssh:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - $SSH_KEY_FINGERPRINT
      - run:
          name: ssh deploy
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "./Netpips.CI/deploy/deploy_server.sh $CIRCLE_BRANCH"

workflows:
  version: 2
  # dev-workflow:
  #   jobs:
  #     - build-simple:
  #         filters:
  #           branches:
  #             ignore:
  #               - staging
  #               - production
  staging-workflow:
    jobs:
      - wait:
          context: staging-ctx
          # filters:
          #   branches:
          #     only:
          #       - staging
      - hold:
          type: approval
          requires:
            - wait
      - display:
          context: staging-ctx
          requires:
            - hold
          # filters:
          #   branches:
          #     only:
          #       - staging
  # staging-workflow:
  #   jobs:
  #     - build-simple:
  #         context: staging-ctx
  #         filters:
  #           branches:
  #             only:
  #               - staging
  #     - deploy-ssh:
  #         context: staging-ctx
  #         requires:
  #           - build-simple
  #         filters:
  #           branches:
  #             only:
  #               - staging