version: 2
jobs:
  quick-build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
      - run: 
          name: Build
          command: dotnet build
      - run:
          name: Test
          command: dotnet test --no-build Netpips.Tests --filter "TestCategory!=Filebot&TestCategory!=ThirdParty"
  say-hello:
    steps:
      - run:
          name: Say Hello
          command: echo Hello

workflows:
  version: 2
  default-workflow:
    jobs:
      - quick-build:
          filters:
            branches:
              ignore:
                - staging
                - production
  staging-workflow:
    jobs:
      - say-hello:
          filters:
            branches:
              only: staging