// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Netpips.Core.Model;

namespace Netpips.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180620162520_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Netpips.Download.Model.DownloadItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Archived")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CanceledAt");

                    b.Property<DateTime>("CompletedAt");

                    b.Property<DateTime>("DownloadedAt");

                    b.Property<string>("FileUrl");

                    b.Property<string>("Hash");

                    b.Property<string>("Name");

                    b.Property<Guid>("OwnerId");

                    b.Property<DateTime>("StartedAt");

                    b.Property<string>("State")
                        .IsRequired();

                    b.Property<string>("Token");

                    b.Property<long>("TotalSize");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.Property<string>("_movedFiles")
                        .HasColumnName("MovedFiles");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("DownloadItems");
                });

            modelBuilder.Entity("Netpips.Identity.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsUnicode(true);

                    b.Property<string>("FamilyName");

                    b.Property<string>("GivenName");

                    b.Property<bool>("IsAdmin");

                    b.Property<string>("Picture");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Netpips.Download.Model.DownloadItem", b =>
                {
                    b.HasOne("Netpips.Identity.Model.User", "Owner")
                        .WithMany("DownloadItems")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
