name: Netpips.Server
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.x'
      - name: Install aria2c
        run: |
          sudo apt-get install -y aria2
          aria2c --version

      - name: Install mediainfo
        run: |
          sudo apt-get install -y mediainfo
          mediainfo --version

      - name: Install transmisstion-remote
        run: |
          sudo apt-get install -y transmission-cli
          sudo apt-get install -y transmission-daemon
          sudo apt-get install -y transmission-common
          transmission-remote --version

      - name: Install filebot
        run: |
          sudo apt-get install -y openjdk-8-jre
          sudo apt-get install -y openjdk-8-jdk
          wget -O filebot.deb 'https://app.filebot.net/download.php?type=deb&arch=amd64'
          dpkg -i filebot.deb
          rm -f   filebot.deb
          filebot -version

      - name: Run unit tests
        run: |
          dotnet build
          dotnet test --filter 'TestCategory=LocalDependency'
  
  release:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          tag_prefix: 'netpips-server-'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release Netpips.Server ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
